---
title: "Data Wrangling Assignment 1"
authors: "Alexander Uitendaal , Milad Ehsan(10732918) , Daan Uittenhout(11057777) and Isabel Slot()"
output:
  html_document: default
pdf_document: default
---

Install and add all packages that will be used for this assignment

```{r}
install.packages(mlbench)
library("mlbench")
library(ggplot2)
library( taRifx )
library("descr")
library(corrplot)

```
 
 
```{r}
# install.packages( "viridis" )    # to install the package, if you've not install it before
library( viridis )

```


```{r}
data("BreastCancer")  #install the right dataset: BreastCancer
View(BreastCancer)

## Missing values 
missing <- is.na(BreastCancer) #Check whether there are missing values
View(missing) 

#There are missing values, so delete these:
BreastCancer2<-na.omit(BreastCancer)
view(BreastCancer2)

# 16 out of 700 (+/- 2%)observations where lost

# install mice pack
# add mice pack to lib
# use imputing to fill the missing data
# create class BreastcancerImputted
BreastcancerImputted <- mice(BreastCancer)
View(BreastcancerImputted)
# sumarize data and class
md.pattern(BreastcancerImputted)
summary(BreastcancerImputted)
BreastCancer2 <- BreastcancerImputted $data


```


render("Assignment1.rmd", output_file = "Assignment1")